[theme]
primaryColor = "#76B900"
backgroundColor = "#080A09"
secondaryBackgroundColor = "#111411"
textColor = "#F4F7F4"
font = "sans-serif"

[server]
headless = true

[browser]
gatherUsageStats = false
